version: '3'

services:
  go-micro:
    build:
      context: ./
    restart: unless-stopped
    container_name: go-micro
    image: go-micro:1.0
    tty: true
    volumes:
      - ./app/:/app
    ports:
      - "50054:50054"
    networks:
      - net-micro

networks:
  net-micro:
    driver: bridge
